version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  lint_code:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint code
          command: npm run lint:fix

  run_tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test

  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build

workflows:
  build_library:
    jobs:
      - lint_code
      - run_tests
      - build
